/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yellowdo_myapplication_MainActivity */

#ifndef _Included_com_yellowdo_myapplication_MainActivity
#define _Included_com_yellowdo_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yellowdo_myapplication_MainActivity
 * Method:    opencv_lib_run
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_yellowdo_myapplication_MainActivity_opencv_1lib_1run
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
